wandb_version: 1

batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688085292.658112
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 16
      - 19
      - 23
      - 37
      4: 3.10.12
      5: 0.15.4
      8:
      - 1
      - 4
      - 5
epochs:
  desc: null
  value: 2
log_step:
  desc: null
  value: 20
val_log_step:
  desc: null
  value: 50
architecture_name:
  desc: null
  value: MLP
dataset_name:
  desc: null
  value: MNIST
